### ISSUE TITLE
图片路径问题

### ISSUE THREAD

**Issue by xieleihan** [hingsli/1x-web-certificate-gkd-v2#2]
老师,其实你可以新建一个仓库,专门用来存放图片,然后,只需要在Markdown中,引用网站的链接,图片就可以正常显示,这是我一个小提议,你看下是否可行

**Comment by hingsli** [comment]
好的，但目前先运行一段时间试试看

**Comment by xieleihan** [comment]
老师，好像崩了

**Comment by hingsli** [comment]
现在好了，刚才没把代码整合好
